// client/src/components/PolicyTable/PolicyTable.vue
<template>
    <div>
      <cv-data-table class="policy-table" :columns="columns" >
        <template slot="data">
          <cv-data-table-row class="policy-row"
           v-for="(row, rowIndex) in this.datarows"
           :key="`${rowIndex}`">
            <cv-data-table-cell class="policy-cell">
              <Policy :id="`${row.data.id}`"
              :title="`${row.data.title}`"
              :summary="`${row.data.summary}`"
              :date_introduced="`${row.data.date_introduced}`"
                 />
            </cv-data-table-cell>
            <!-- <template slot="expandedContent">
            {{ row.description }}
            </template> -->
          </cv-data-table-row>
        </template>
      </cv-data-table>
    </div>
</template>

<script>
import Policy from '@/components/Policy';

export default {
  name: "PolicyTable",
  props: {
    rows: Array,
  },
  components: {
    Policy,
  },
  data() {
    console.log(`items : ${this.rows.length} -> ${this.rows[0].title}`);
    return {
      columns: [`POLICIES (${this.rows.length})`],
      title: "",
      helperText: "",
      datarows: this.rows.map((row) => ({
        data: row,
        description: row.summary,
      })),
    };
  },
};
</script>

<style lang="scss" scoped>
@import '@/styles/carbon-overrides';
.policy-table{
  background-color: $ui-01;
  .policy-row{
    padding: 0;
    margin: 0;
    .policy-cell{
      padding: 0;
      margin: 0;
      background-color: $ui-01;
    }
  }
}
</style>

// react/client/src/PolicyTable.js
import React from 'react'
import {useSelector} from 'react-redux'
import {Column, Grid, Row} from 'carbon-components-react'
import PolicyTableItem from './PolicyTableItem'

const PolicyTable = () => {
  const { items } = useSelector(({policyList}) => policyList)

  const renderEmptyPolicyTable = () => {
    return (
      <div data-testid={'emptyPolicyTable'}>
        No Policies Available.
      </div>
    )
  }

  const renderItem = (item, index) => {
    return (
      <Row key={item.id} data-testid={'policyItem'} className={'policy-row'}>
        <Column className={'policy-cell'}>
          <PolicyTableItem title={item.title} summary={item.summary} dateIntroduced={item.date_introduced} rowNumber={index}/>
        </Column>
      </Row>
    )
  }

  if (!items || !items.length) {
    return renderEmptyPolicyTable()
  }
  return (
    <div data-testid={'policyTable'}>
      <Grid className={'policy-table'}>
        <Row className={'policy-title-row'}>
          <Column>{`POLICIES: (${items.length})`}</Column>
        </Row>
        {items.map(renderItem)}
      </Grid>
    </div>
  )
}

export default PolicyTable
